title: Handley-Lab
email: wh260@cam.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Handley Lab website. We are a research group based in the Institute of Astronomy at the University of Cambridge. Our research focuses on Bayesian statistics, machine learning, and data analysis for astrophysics, cosmology and high energy physics.
domain: "handley-lab.co.uk"
url: "https://handley-lab.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  handley-lab

# Build settings
theme: minima
  skin: dark
plugins:
  - jekyll-feed
  - jekyll-seo-tag
