from google import genai
from io import BytesIO
import os
import xml.etree.ElementTree as ET
import re
import feedparser
import requests
import yaml

text_model = "gemini-1.5-pro"
image_model = "imagen-3.0-generate-002"
url_model = "https://deepmind.google/technologies/gemini/"
client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

imagename = f'/assets/images/index.png'
prompt_save = f'/prompts/posts/index.md'
image_prompt_save = f'/prompts/images/index.md'

# Get arxiv papers
print(f"Getting arxiv papers")
url = "https://arxiv.org/a/handley_w_1.atom"
response = requests.get(url)
xml_content = response.content
root = ET.fromstring(xml_content)
ns = {"atom": "http://www.w3.org/2005/Atom"}
entries = root.findall("atom:entry", ns)
ids = [entry.find("atom:id", ns).text for entry in entries]
ids = [re.sub(r"http://arxiv.org/abs/", "", id) for id in ids]
ids = [re.sub(r"v[0-9]+$", "", id) for id in ids]
id_list = ','.join(ids)
api_url = f"http://export.arxiv.org/api/query?id_list={id_list}&max_results={len(ids)}"
response = requests.get(api_url)
feed = feedparser.parse(response.content)

def markdown(entry):
    url = entry.id
    arxiv = re.sub(r"http://arxiv.org/abs/", "", url)
    arxiv = re.sub(r"v[0-9]+$", "", arxiv)
    prompt = f"""# {entry.title.replace("\n", " ")}

[{arxiv}](entry.id)\n

## Abstract\n
{entry.summary.replace("\n", " ")}\n

## Authors\n
{', '.join(author.name for author in entry.authors)}\n
  
## Published\n
{entry.published}\n
"""
    return prompt

print(f"Gathering other data")
with open('assets/group/group.yaml', 'r') as f:
    group = f.read()
    group = yaml.safe_load(group)

with open('/home/will/archive/rs_renewal/research_proposal/research_proposal.tex', 'r') as f:
    tex = f.read()

with open('index.md', 'r') as f:
    index = f.read()

prompt = f"""
Title: Update and Enhance Our Research Group Summary for the Website
====================================================================================
Our goal is to create a concise, engaging, and factually accurate summary that captures our research group’s identity, achievements, and future ambitions—with a special focus on our artificial intelligence initiatives.
====================================================================================
Output Format (Markdown):
------------------------------------------------------------------------------------
---
layout: home
---

![AI generated image]({imagename})\n
<!-- START OF WEBSITE SUMMARY -->
<!-- END OF WEBSITE SUMMARY -->\n
Content generated by [{text_model}]({url_model}) using [this prompt]({prompt_save}).\n
Image generated by [{image_model}]({url_model}) using [this prompt]({image_prompt_save}).
------------------------------------------------------------------------------------
====================================================================================
Section 1: Content Creation Instructions
====================================================================================
1. **Compose the Website Summary:**
   - Write a clear, engaging narrative that is accessible to both experts and the general public.
   - The summary should include the following elements:
     - **Introduction:** Briefly describe who we are, our research areas, and our mission.
     - **Research Focus:** Highlight our primary research themes, innovative methodologies, and technical contributions, with special emphasis on AI.
     - **Highlight Achievements:** Mention key publications and significant milestones that underscore the impact of our work.
     - **Outline Future Directions:** Summarize emerging projects and research avenues.
   - When referring to any research topic, include a Markdown-formatted link to a relevant arXiv paper (e.g., [non-parametric reconstructions](https://arxiv.org/abs/2503.08658)).
   - Use bullet points, subheadings, or other formatting to enhance readability.
   - The name of the group is 'The Handley Research Group.'

2. **Integrate Data from Multiple Sources:**
   - **Published Papers (Markdown):**  A list of all our published papers. These papers are available on arXiv, and you should include a link to each paper mentioned in the narrative.
   - **Research Group Structure (YAML):**  The members of our group and our organizational history. There will not be a link to this, but you can use it to inform the narrative.
   - **Future Research Directions (LaTeX):**  A successful grant application detailing our future research plans. There will not be a link to this, but you can use it to inform the narrative. Do not mention the grant application.
   - Seamlessly weave insights from these three sources into a cohesive and compelling narrative.

3. **Emphasize AI Research:**
   - Give particular attention to our work in artificial intelligence. When discussing AI-related topics, ensure to reference illustrative arXiv papers using proper Markdown link formatting.

4. **Final Formatting Requirements:**
   - The output must be plain Markdown; do not wrap it in Markdown code fences.
   - Preserve the YAML front matter exactly as provided.

====================================================================================
Section 2: Provided Data for Integration
====================================================================================
1. **List of Published Papers:**  
   ```markdown
   { '\n\n'.join([markdown(entry) for entry in feed.entries]) }
   ```

2. **Research Group Structure:**  
   ```yaml
   {yaml.dump(group)}
   ```

3. **Future Research Directions (from our Grant Application):**  
   ```tex
   {tex}
   ```

====================================================================================
Final Output Requirements
====================================================================================

- Combine all data sources to create a seamless, engaging narrative.
- Follow the exact Markdown output format provided at the top.
- Do not include any extra explanation, commentary, or wrapping beyond the specified Markdown.
- Ensure every reference to a research topic includes a correctly formatted Markdown link (e.g., [AI methodologies](https://arxiv.org/abs/2503.08658)), and validate that it corresponds to the correct paper in the list of Published papers.
- Utilize all provided sources to construct a narrative that is both cohesive and faithful to our research contributions.
- The tone should be professional, accessible, and engaging.

Generate only the final Markdown output that meets all these requirements.
"""

print(f"Generating content")
response = client.models.generate_content(model=text_model, contents=prompt) 
content = response.text


print(f"Generating image prompt")
pre_image_prompt=f"""
Generate a prompt which will generate an image to headline a website with this text:
```markdown
{content}
```
The image should be abstract, and not try to relay any quantitative information (so no graphs, numbers or text). It should be visually appealing and related to the topic of the paper.
"""
response = client.models.generate_content(model=text_model, contents=pre_image_prompt)
image_prompt = response.text

print(f"Generating image")
response = client.models.generate_images(model=image_model, prompt=image_prompt, config=genai.types.GenerateImagesConfig(aspect_ratio="16:9", number_of_images=1))
 
from PIL import Image
image = Image.open(BytesIO(
    response.generated_images[0].image.image_bytes
    ))
 
# Save page
with open('index.md', 'w') as f:
    f.write(content)
print(f"Page saved to index.md")

# Save image
image.save(f'.{imagename}')
print(f"Image saved to .{imagename}")

# Save prompts
with open(f'.{prompt_save}', 'w') as f:
    f.write(prompt)
print(f"Prompt saved to .{prompt_save}")

with open(f'.{image_prompt_save}', 'w') as f:
    f.write(image_prompt)
print(f"Image prompt saved to .{image_prompt_save}")
